# Generated by Django 5.1.2 on 2024-12-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Main heading text for the banner.', max_length=255)),
                ('subheading', models.CharField(help_text='Subheading or location for the banner.', max_length=255)),
                ('image', models.ImageField(help_text='Upload an image with rendered size 520x395 px, aspect ratio 104:79.', upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://youtube.com/your-property-tour-video')),
                ('properties_sold', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('satisfied_clients', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.FloatField(default=0)),
                ('emi_starts_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('made_to_order', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimensions', models.CharField(blank=True, help_text='Product dimensions (e.g., LxWxH)', max_length=255, null=True)),
                ('maintenance', models.TextField(blank=True, help_text='Maintenance guidelines for the product', null=True)),
                ('warranty_summary', models.TextField(blank=True, help_text='Warranty details for the product', null=True)),
                ('return_policy', models.TextField(blank=True, help_text='Return policy for the product', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload a logo with a rendered size of 212x50 px, aspect ratio of 106:25. The intrinsic size should be 1025x243 px.', upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], default='facebook', max_length=50)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the customization option (e.g., Polish Finish, Size)', max_length=255)),
                ('choices', models.JSONField(default=dict, help_text="Choices for customization as a JSON object (e.g., {'Queen': 100, 'King': 150})")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature name (e.g., Key Feature)', max_length=255)),
                ('value', models.TextField(blank=True, help_text='Details or description of the feature', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.service')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='service_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.serviceoption'),
        ),
    ]
