# Generated by Django 5.1.2 on 2024-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_short_description_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the video section', max_length=255)),
                ('subtitle', models.CharField(help_text='Subtitle or tagline of the video section', max_length=255)),
                ('video_thumbnail', models.ImageField(help_text='Thumbnail image for the video', upload_to='videos/')),
                ('video_url', models.URLField(help_text='URL of the video (e.g., YouTube link)')),
            ],
        ),
        migrations.DeleteModel(
            name='FunFact',
        ),
    ]
