# Generated by Django 5.1.2 on 2024-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_videosection_delete_funfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title for the fun fact (e.g., 'Properties Sold')", max_length=255)),
                ('value', models.PositiveIntegerField(help_text='Numerical value for the fun fact (e.g., 34)')),
                ('description', models.CharField(help_text="Short description (e.g., 'Finished Now')", max_length=255)),
            ],
        ),
    ]
