# Generated by Django 5.1.2 on 2024-12-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_funfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosection',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of the video (e.g., YouTube link)', null=True),
        ),
    ]
